### ISSUE TITLE
django 2 compatibility

### ISSUE THREAD

**Issue by juliGer** [NilCoalescing/djangochannelsrestframework#133]
hello I was trying to install the library but I am having compatibility problems since in the project that I am working on it is with django 2 and at the moment it is not planned to change to django 3 or higher

I was reading and in django-channels there is compatibility with django 2

Is there a version of the django channels rest framework library that is compatible with django 2 or is it planned to be?  thanks greetings

**Comment by hishnash** [comment]
Sorry this took me aghast to ge around shipping a release this this. 1.1 now includes this vix.
