### ISSUE TITLE
consumers.py: has_permission() got an unexpected keyword argument 'scope'

### ISSUE THREAD

**Issue by juliGer** [NilCoalescing/djangochannelsrestframework#135]
Hi, I was trying to use the library via view_as_consumer and it compiled fine.
Then when from the frontend I send a send I get the following error 

`has_permission() got an unexpected keyword argument 'scope'`.

The message I sent to the ws was as follows 
```
const chatSocket = new WebSocket('ws://localhost:8090/ws');
        chatSocket.onopen = () => {
            chatSocket.send(
                JSON.stringify({
                    action: "list",
                    request_id: new Date().getTime()
                })
            );
        };
```
May be I am missing some configuration ? I leave the configuration and the complete log

Thanks and greetings!

asgi.py
```
import os
from django.conf.urls import url
from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
from djangochannelsrestframework.consumers import view_as_consumer
from api.views import ChatSessionViewSet
from channels.http import AsgiHandler

os.environ.setdefault('DJANGO_SETTINGS_MODULE', '{{ project_name }}.settings')

application = ProtocolTypeRouter({
    "websocket": AuthMiddlewareStack(
        URLRouter([
            url(r"ws", view_as_consumer(ChatSessionViewSet)),
        ])
    ),
})

```

![image](https://user-images.githubusercontent.com/49050724/167158170-d46ccd19-597d-407e-abc4-000baa4639e3.png)

**Comment by hishnash** [comment]
Hi @juliGer  can you try  adding `as_view()`.

```python
application = ProtocolTypeRouter({
    "websocket": AuthMiddlewareStack(
        URLRouter([
            url(r"ws", view_as_consumer(ChatSessionViewSet.as_view())),
        ])
    ),
})
```

I think this was missed in the docs.

**Comment by juliGer** [comment]
Hi, I tried it but it didn't work :( My viewset is a subclass of viewset.Viewset, I don't know if that has something to do with it. 
Also I have authentication_classes,permission_classes maybe this is causing the problem and I need to add some more configuration ? 

Below I leave the code of the view set and what classes it extends and what it uses.

![image](https://user-images.githubusercontent.com/49050724/167233223-5f2274d8-9b2b-425c-b1f3-bb90ffd5776a.png)
![image](https://user-images.githubusercontent.com/49050724/167233217-16754efa-11a1-420c-b3fb-b60ef3e7e0bd.png)
![image](https://user-images.githubusercontent.com/49050724/167233239-3634bfbe-5dcd-4d2b-86ed-38a6662c41a8.png)
![image](https://user-images.githubusercontent.com/49050724/167233248-8213ac92-de77-4dac-a3e2-45e2ec201103.png)

I also tried to create a class that extends ApiView without anything and it didn't work either, and lastly I tried to add `"http":AsgiHandler()` but it didn't work either.

**Comment by hishnash** [comment]
in settings have you defined a `DEFAULT_PERMISSION_CLASSES`?

**Comment by juliGer** [comment]
Yes, also the default authentication the problem is originating in the following code in the consumers.py of the library, I understand that but I don't know what the problem is
![image](https://user-images.githubusercontent.com/49050724/167275847-80b1f600-d888-4636-932b-54bfae514245.png)

**Comment by juliGer** [comment]
I put a pdb in the consumers.py file of the library on line 110 and I get the following

![image](https://user-images.githubusercontent.com/49050724/167336460-26993b3a-e585-4e0c-8cd8-34a8624ceae7.png)

Apparently it is receiving a `rest_framework.permissions.IsAuthenticated` object, that in theory is correct the problem I am seeing is that the has_permission function receives only two parameters that are request and view , it seems to me that there is the problem is being sent parameters not received

The has_permission function is from the IsAuthenticated class which is from rest_framework and it receives only those arguments

@hishnash is it ok that he receives that class? If so, would we have to update this part in consumers.py? Thanks greetings!

**Comment by juliGer** [comment]
Reviewing the library files I found
The problem was that the following was not defined in the settings and since it was not defined, it was using the authorization classes inside rest_framework
``` 
DJANGO_CHANNELS_REST_API = {
    'DEFAULT_PERMISSION_CLASSES': ('djangochannelsrestframework.permissions.IsAuthenticated',)}
 ```
With this it worked I think it is correct, could you please confirm it for me? And if this is so, it would be nice to add it to the documentation :)

**Comment by hishnash** [comment]
That is correct, yer we should not be pulling the `REST FRAMEWORK` class as it will always fail.
