### ISSUE TITLE
Add link to ReadTheDocs in GitHub Project Description

### ISSUE THREAD

**Issue by johnthagen** [NilCoalescing/djangochannelsrestframework#170]
Add https://djangochannelsrestframework.readthedocs.io/en/latest/ to repo's description. E.g.:

![image](https://user-images.githubusercontent.com/10340167/230426401-4f9345df-8e14-4790-b7ac-b5f702f35374.png)

This will make it easier for new users to quickly find the documentation as it's in a familiar/common location.

**Comment by hishnash** [comment]
I have updated GH, was not aware this was a feature on GH.
